// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzaafqyvcjwmtjrmmpdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YWFmcXl2Y2p3bXRqcm1tcGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzYwMTUsImV4cCI6MjA1ODExMjAxNX0.OBmdDbYBRm3kBnuypXQYJ86dzMRJEWN_lAhKbHZk_Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);